#!/bin/bash

# Launcher Desktop Handler Script
# 
# This script handles myapp:// URIs generated by the launcher service.
# It's registered as a desktop URI handler and executes commands on the user's machine.
#
# Usage: This script is called automatically by the desktop environment
#        when a myapp:// URI is opened (e.g., via web browser)
#
# Setup: Register with: xdg-mime default launcher-handler.desktop x-scheme-handler/myapp

echo "LAUNCH_TOOL.SH - SCRIPT VERSION 5-TEMP-SCRIPT - URI: $1" >> ~/launch_tool_log.txt

uri="$1"
# Remove the scheme (e.g., "myapp://")
command="${uri#myapp://}"

# Optional: Parse the command or log it
echo "Executing command from URI: $command" >> ~/launch_tool_log.txt

# Example: Launch based on URI content
case "$command" in
  launch_tool/*)
    tool_arg_encoded="${command#launch_tool/}"
    # URL decode the argument
    tool_arg_decoded=$(printf '%b' "${tool_arg_encoded//%/\\x}")

    echo "Received encoded arg: $tool_arg_encoded" >> ~/launch_tool_log.txt
    echo "Decoded command to execute: $tool_arg_decoded" >> ~/launch_tool_log.txt

    # Execute the decoded command in a new terminal.
    # The terminal will run the command, then wait for Enter before closing.
    gnome-terminal -- bash -c "$tool_arg_decoded; echo; echo '--- Command finished. Press Enter to close this terminal. ---'; read"
    ;;
  *)
    echo "Unrecognized command: $command" >> ~/launch_tool_log.txt
    ;;
esac
